import React, { createContext, useState, useContext, useEffect } from 'react';
import { getSupportedLanguages, getTranslations } from '../services/languageService';

// Types
type Language = 'en' | 'ru' | 'fr' | 'es' | 'de' | 'it';

interface Translations {
  [key: string]: string;
}

export interface LanguageContextType {
  language: Language;
  t: (key: string) => string;
  changeLanguage: (lang: Language) => void;
  supportedLanguages: Language[];
}

const defaultTranslations: {[key in Language]: Translations} = {
  en: {
    welcome: 'Welcome',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    loading: 'Loading...',
    cities: 'Cities',
    search: 'Search',
    profile: 'Profile',
    city: 'City',
    pointsOfInterest: 'Points of Interest',
    routes: 'Routes',
    events: 'Events',
    favorites: 'Favorites',
    loggedInAs: 'Logged in as',
    noFavorites: 'You have no favorites yet',
    cityDetails: 'City Details',
    pointDetails: 'Point Details',
    routeDetails: 'Route Details',
    eventDetails: 'Event Details',
    noDateAvailable: 'No date available',
    relatedPoints: 'Related Points',
    relatedRoutes: 'Related Routes',
    relatedEvents: 'Related Events',
    noRelatedItems: 'No related items found',
    error: 'Error',
    cityNotFound: 'City not found',
    pointNotFound: 'Point not found',
    routeNotFound: 'Route not found',
    eventNotFound: 'Event not found',
    errorFetchingCityData: 'Error fetching city data',
    errorFetchingPointData: 'Error fetching point data',
    errorFetchingRouteData: 'Error fetching route data',
    errorFetchingEventData: 'Error fetching event data',
    unexpectedError: 'An unexpected error occurred',
    home: 'Home',
    language: 'Language',
    selectLanguage: 'Select Language',
    or: 'or',
    continueWithGoogle: 'Continue with Google',
    goToSignIn: 'Already have an account? Sign in',
    goToSignUp: 'Don\'t have an account? Sign up',
    notFound: 'Page Not Found',
    viewAllCities: 'View All Cities',
    seeAllPoints: 'See All Points',
    seeAllRoutes: 'See All Routes',
    seeAllEvents: 'See All Events',
    location: 'Location',
    duration: 'Duration',
    difficulty: 'Difficulty',
    signedOut: 'Signed Out',
    youHaveBeenSignedOut: 'You have been signed out successfully',
    failedToSignOut: 'Failed to sign out. Please try again',
    startDate: 'Start Date',
    endDate: 'End Date'
  },
  ru: {
    welcome: 'Добро пожаловать',
    signIn: 'Войти',
    signUp: 'Зарегистрироваться',
    signOut: 'Выйти',
    email: 'Электронная почта',
    password: 'Пароль',
    name: 'Имя',
    loading: 'Загрузка...',
    cities: 'Города',
    search: 'Поиск',
    profile: 'Профиль',
    city: 'Город',
    pointsOfInterest: 'Достопримечательности',
    routes: 'Маршруты',
    events: 'События',
    favorites: 'Избранное',
    loggedInAs: 'Вы вошли как',
    noFavorites: 'У вас пока нет избранного',
    cityDetails: 'Информация о городе',
    pointDetails: 'Информация о достопримечательности',
    routeDetails: 'Информация о маршруте',
    eventDetails: 'Информация о событии',
    noDateAvailable: 'Дата не указана',
    relatedPoints: 'Связанные достопримечательности',
    relatedRoutes: 'Связанные маршруты',
    relatedEvents: 'Связанные события',
    noRelatedItems: 'Связанные элементы не найдены',
    error: 'Ошибка',
    cityNotFound: 'Город не найден',
    pointNotFound: 'Достопримечательность не найдена',
    routeNotFound: 'Маршрут не найден',
    eventNotFound: 'Событие не найдено',
    errorFetchingCityData: 'Ошибка при получении данных о городе',
    errorFetchingPointData: 'Ошибка при получении данных о достопримечательности',
    errorFetchingRouteData: 'Ошибка при получении данных о маршруте',
    errorFetchingEventData: 'Ошибка при получении данных о событии',
    unexpectedError: 'Произошла непредвиденная ошибка',
    home: 'Главная',
    language: 'Язык',
    selectLanguage: 'Выберите язык',
    or: 'или',
    continueWithGoogle: 'Продолжить с Google',
    goToSignIn: 'Уже есть аккаунт? Войти',
    goToSignUp: 'Нет аккаунта? Зарегистрироваться',
    notFound: 'Страница не найдена',
    viewAllCities: 'Просмотреть все города',
    seeAllPoints: 'Смотреть все достопримечательности',
    seeAllRoutes: 'Смотреть все маршруты',
    seeAllEvents: 'Смотреть все события',
    location: 'Местоположение',
    duration: 'Продолжительность',
    difficulty: 'Сложность',
    signedOut: 'Выход выполнен',
    youHaveBeenSignedOut: 'Вы успешно вышли из системы',
    failedToSignOut: 'Не удалось выйти. Пожалуйста, попробуйте еще раз',
    startDate: 'Дата начала',
    endDate: 'Дата окончания'
  },
  fr: {
    welcome: 'Bienvenue',
    signIn: 'Se connecter',
    signUp: 'S\'inscrire',
    signOut: 'Se déconnecter',
    email: 'Courriel',
    password: 'Mot de passe',
    name: 'Nom',
    loading: 'Chargement...',
    cities: 'Villes',
    search: 'Rechercher',
    profile: 'Profil',
    city: 'Ville',
    pointsOfInterest: 'Points d\'intérêt',
    routes: 'Routes',
    events: 'Événements',
    favorites: 'Favoris',
    loggedInAs: 'Connecté en tant que',
    noFavorites: 'Vous n\'avez pas encore de favoris',
    cityDetails: 'Détails de la ville',
    pointDetails: 'Détails du point d\'intérêt',
    routeDetails: 'Détails du trajet',
    eventDetails: 'Détails de l\'événement',
    noDateAvailable: 'Aucune date disponible',
    relatedPoints: 'Points d\'intérêt liés',
    relatedRoutes: 'Routes liées',
    relatedEvents: 'Événements liés',
    noRelatedItems: 'Aucun élément lié trouvé',
    error: 'Erreur',
    cityNotFound: 'Ville non trouvée',
    pointNotFound: 'Point d\'intérêt non trouvé',
    routeNotFound: 'Trajet non trouvé',
    eventNotFound: 'Événement non trouvé',
    errorFetchingCityData: 'Erreur lors de la récupération des données de la ville',
    errorFetchingPointData: 'Erreur lors de la récupération des données du point d\'intérêt',
    errorFetchingRouteData: 'Erreur lors de la récupération des données du trajet',
    errorFetchingEventData: 'Erreur lors de la récupération des données de l\'événement',
    unexpectedError: 'Une erreur inattendue s\'est produite',
    home: 'Accueil',
    language: 'Langue',
    selectLanguage: 'Sélectionner la langue',
    or: 'ou',
    continueWithGoogle: 'Continuer avec Google',
    goToSignIn: 'Déjà un compte ? Se connecter',
    goToSignUp: 'Pas de compte ? S\'inscrire',
    notFound: 'Page non trouvée',
    viewAllCities: 'Voir toutes les villes',
    seeAllPoints: 'Voir tous les points d\'intérêt',
    seeAllRoutes: 'Voir tous les trajets',
    seeAllEvents: 'Voir tous les événements',
    location: 'Localisation',
    duration: 'Durée',
    difficulty: 'Difficulté',
    signedOut: 'Déconnecté',
    youHaveBeenSignedOut: 'Vous avez été déconnecté avec succès',
    failedToSignOut: 'Échec de la déconnexion. Veuillez réessayer',
    startDate: 'Date de début',
    endDate: 'Date de fin'
  },
  es: {
    welcome: 'Bienvenido',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    signOut: 'Cerrar Sesión',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    name: 'Nombre',
    loading: 'Cargando...',
    cities: 'Ciudades',
    search: 'Buscar',
    profile: 'Perfil',
    city: 'Ciudad',
    pointsOfInterest: 'Puntos de Interés',
    routes: 'Rutas',
    events: 'Eventos',
    favorites: 'Favoritos',
    loggedInAs: 'Inició sesión como',
    noFavorites: 'Aún no tiene favoritos',
    cityDetails: 'Detalles de la Ciudad',
    pointDetails: 'Detalles del Punto de Interés',
    routeDetails: 'Detalles de la Ruta',
    eventDetails: 'Detalles del Evento',
    noDateAvailable: 'No hay fecha disponible',
    relatedPoints: 'Puntos de Interés Relacionados',
    relatedRoutes: 'Rutas Relacionadas',
    relatedEvents: 'Eventos Relacionados',
    noRelatedItems: 'No se encontraron elementos relacionados',
    error: 'Error',
    cityNotFound: 'Ciudad no encontrada',
    pointNotFound: 'Punto de Interés no encontrado',
    routeNotFound: 'Ruta no encontrada',
    eventNotFound: 'Evento no encontrado',
    errorFetchingCityData: 'Error al obtener datos de la ciudad',
    errorFetchingPointData: 'Error al obtener datos del punto de interés',
    errorFetchingRouteData: 'Error al obtener datos de la ruta',
    errorFetchingEventData: 'Error al obtener datos del evento',
    unexpectedError: 'Se produjo un error inesperado',
    home: 'Inicio',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    or: 'o',
    continueWithGoogle: 'Continuar con Google',
    goToSignIn: 'Ya tienes una cuenta? Iniciar Sesión',
    goToSignUp: 'No tienes una cuenta? Registrarse',
    notFound: 'Página no encontrada',
    viewAllCities: 'Ver Todas las Ciudades',
    seeAllPoints: 'Ver Todos los Puntos de Interés',
    seeAllRoutes: 'Ver Todas las Rutas',
    seeAllEvents: 'Ver Todos los Eventos',
    location: 'Ubicación',
    duration: 'Duración',
    difficulty: 'Dificultad',
    signedOut: 'Desconectado',
    youHaveBeenSignedOut: 'Se ha desconectado con éxito',
    failedToSignOut: 'No se pudo desconectar. Por favor, inténtalo de nuevo',
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Fin'
  },
  de: {
    welcome: 'Willkommen',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    signOut: 'Abmelden',
    email: 'E-Mail',
    password: 'Passwort',
    name: 'Name',
    loading: 'Laden...',
    cities: 'Städte',
    search: 'Suchen',
    profile: 'Profil',
    city: 'Stadt',
    pointsOfInterest: 'Interessentengruppen',
    routes: 'Routen',
    events: 'Veranstaltungen',
    favorites: 'Favoriten',
    loggedInAs: 'Angemeldet als',
    noFavorites: 'Sie haben noch keine Favoriten',
    cityDetails: 'Stadtdetails',
    pointDetails: 'Punktdetails',
    routeDetails: 'Routendetails',
    eventDetails: 'Veranstaltungsdetails',
    noDateAvailable: 'Keine Daten verfügbar',
    relatedPoints: 'Verwandte Punkte',
    relatedRoutes: 'Verwandte Routen',
    relatedEvents: 'Verwandte Veranstaltungen',
    noRelatedItems: 'Keine verknüpften Elemente gefunden',
    error: 'Fehler',
    cityNotFound: 'Stadt nicht gefunden',
    pointNotFound: 'Punkt nicht gefunden',
    routeNotFound: 'Rute nicht gefunden',
    eventNotFound: 'Veranstaltung nicht gefunden',
    errorFetchingCityData: 'Fehler beim Abrufen der Stadt-Daten',
    errorFetchingPointData: 'Fehler beim Abrufen der Punkt-Daten',
    errorFetchingRouteData: 'Fehler beim Abrufen der Rute-Daten',
    errorFetchingEventData: 'Fehler beim Abrufen der Veranstaltungs-Daten',
    unexpectedError: 'Ein unerwarteter Fehler ist aufgetreten',
    home: 'Startseite',
    language: 'Sprache',
    selectLanguage: 'Sprache auswählen',
    or: 'oder',
    continueWithGoogle: 'Mit Google fortfahren',
    goToSignIn: 'Bereits ein Konto? Anmelden',
    goToSignUp: 'Kein Konto? Registrieren',
    notFound: 'Seite nicht gefunden',
    viewAllCities: 'Alle Städte anzeigen',
    seeAllPoints: 'Alle Punkte anzeigen',
    seeAllRoutes: 'Alle Routen anzeigen',
    seeAllEvents: 'Alle Veranstaltungen anzeigen',
    location: 'Ort',
    duration: 'Dauer',
    difficulty: 'Schwierigkeit',
    signedOut: 'Abgemeldet',
    youHaveBeenSignedOut: 'Sie wurden erfolgreich abgemeldet',
    failedToSignOut: 'Abmeldung fehlgeschlagen. Bitte versuchen Sie es erneut',
    startDate: 'Startdatum',
    endDate: 'Enddatum'
  },
  it: {
    welcome: 'Benvenuto',
    signIn: 'Accedi',
    signUp: 'Registrati',
    signOut: 'Esci',
    email: 'Email',
    password: 'Password',
    name: 'Nome',
    loading: 'Caricamento...',
    cities: 'Città',
    search: 'Cerca',
    profile: 'Profilo',
    city: 'Città',
    pointsOfInterest: 'Punti d\'interesse',
    routes: 'Route',
    events: 'Eventi',
    favorites: 'Preferiti',
    loggedInAs: 'Connesso come',
    noFavorites: 'Non hai ancora preferiti',
    cityDetails: 'Dettagli della città',
    pointDetails: 'Dettagli del punto d\'interesse',
    routeDetails: 'Dettagli della route',
    eventDetails: 'Dettagli dell\'evento',
    noDateAvailable: 'Nessuna data disponibile',
    relatedPoints: 'Punti d\'interesse correlati',
    relatedRoutes: 'Route correlate',
    relatedEvents: 'Eventi correlati',
    noRelatedItems: 'Nessun elemento correlato trovato',
    error: 'Errore',
    cityNotFound: 'Città non trovata',
    pointNotFound: 'Punto d\'interesse non trovato',
    routeNotFound: 'Route non trovata',
    eventNotFound: 'Evento non trovato',
    errorFetchingCityData: 'Errore durante il recupero dei dati della città',
    errorFetchingPointData: 'Errore durante il recupero dei dati del punto d\'interesse',
    errorFetchingRouteData: 'Errore durante il recupero dei dati della route',
    errorFetchingEventData: 'Errore durante il recupero dei dati dell\'evento',
    unexpectedError: 'Si è verificato un errore inaspettato',
    home: 'Home',
    language: 'Lingua',
    selectLanguage: 'Seleziona Lingua',
    or: 'o',
    continueWithGoogle: 'Continua con Google',
    goToSignIn: 'Hai già un account? Accedi',
    goToSignUp: 'Non hai un account? Registrati',
    notFound: 'Pagina non trovata',
    viewAllCities: 'Visualizza tutte le città',
    seeAllPoints: 'Visualizza tutti i punti d\'interesse',
    seeAllRoutes: 'Visualizza tutte le route',
    seeAllEvents: 'Visualizza tutti gli eventi',
    location: 'Posizione',
    duration: 'Durata',
    difficulty: 'Difficoltà',
    signedOut: 'Disconnesso',
    youHaveBeenSignedOut: 'Sei stato disconnesso con successo',
    failedToSignOut: 'Impossibile disconnettersi. Riprova',
    startDate: 'Data di inizio',
    endDate: 'Data di fine'
  }
};

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('holyWandererLanguage');
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ru' || savedLanguage === 'fr' || savedLanguage === 'es' || savedLanguage === 'de' || savedLanguage === 'it')) {
      setLanguageState(savedLanguage as Language);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('holyWandererLanguage', lang);
  };

  const t = (key: string): string => {
    return defaultTranslations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage: setLanguage, supportedLanguages: getSupportedLanguages() }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
